spring:
  application:
    name: apf-offentlig
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

springdoc:
  swagger-ui:
    enabled: true
