spring:
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    path: /apidoc.yaml
