openapi: 3.0.1
info:
  title: Pensjon AFP-offentlig
  description: For å kunne bruke tjenesten må scope i autentiseringen mot Maskinporten
    settes til:`nav:pensjon/v1/tpregisteret`. Inneholder tjenester for å behandle en AFP-offentlig
    søknad.
  version: 1.0.0
servers:
  - url: https://template.value/template/value
paths:
  /harAFPoffentlig:
    get:
      security:
        - bearerAuth: [ ]
      description: Sjekker hvis søker/person har AFP offentlig
      operationId: harAFPoffentlig
      parameters:
        #        - name: Authorization
        #          in: header
        #          description: Format - byte. Standard Authorization header som inneholder et
        #            Base64-kodet Bearer-token (JWT-aksesstoken) utstedt av Maskinporten (Difi).
        #            Verdien må starte med "Bearer ", deretter følger tokenstrengen.
        #          required: true
        #          schema:
        #            type: string
        - name: fnr
          in: header
          description: Format - String 11.
          required: true
          schema:
            type: string
        - name: correlationId
          in: header
          description: Format - UUID, correlationId
          required: false
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BooleanResult'
components:
  schemas:
    BooleanResult:
      title: Result
      type: object
      properties:
        value:
          type: boolean
          description: Informasjon om søker har afp-offentlig (true hvis ja, nei ellers)
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: [ ]
