apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: afp-offentlig
  namespace: pensjonsamhandling
  labels:
    "team": pensjonsamhandling
spec:
  image: {{ image }}
  ingresses:
    - https://afp-offentlig.nav.no
  maskinporten:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: "tp-api.prod-fss-pub.nais.io"
  liveness:
    path: actuator/health/liveness
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: actuator/health/readiness
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
  env:
    - name: TP_FSS_SCOPE
      value: api://prod-fss.samhandler.tp/.default
    - name: TP_FSS_URL
      value: https://tp-api.prod-fss-pub.nais.io
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: LOGGING_CONFIG
      value: classpath:logback-spring.xml
    - name: ENVIRONMENT_NAME
      value: p
