name: "Deploy to dev"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Which version to deploy (e.g. 2020.01.01-12.55-a1b2c3d4e5f6)"
        required: true
      q1:
        description: 'Q1'
        required: true
        default: true
        type: boolean
      q2:
        description: 'Q2'
        required: true
        default: true
        type: boolean


jobs:

  deployAppToQ1:
    permissions:
      contents: "read"
      id-token: "write"
    name: "Deploy to dev-q1"
    if: inputs.q1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Q1 dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev.yaml
          IMAGE: ghcr.io/${{ github.repository }}:${{ inputs.version }}

  deployAppToQ2:
    permissions:
      contents: "read"
      id-token: "write"
    name: "Deploy to dev-q2"
    if: inputs.q2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Q2 dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev-q2.yaml
          IMAGE: ghcr.io/${{ github.repository }}:${{ inputs.version }}
