name: "Deploy to production"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Which version to deploy (e.g. 2020.01.01-a1b2c3d4e5f6)"
        required: true

jobs:
  enforceMainBranch:
    name: "Enforce Main branch"
    runs-on: ubuntu-latest
    steps:
      - if: github.ref != 'refs/heads/main'
        run: exit 1
  deployProd:
    needs: enforceMainBranch
    permissions:
      contents: "read"
      id-token: "write"
    name: "Deploy to Prod"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/prod.yaml
          IMAGE: ghcr.io/${{ github.repository }}:${{ inputs.version }}
          TEAM: pensjonsamhandling
