name: "Build afp-offentlig"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and release
    permissions:
      packages: write
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      # Build
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gradle clean build

      # Build image
      - name: Nais docker-build
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pensjonsamhandling
          tag: ${{ github.event.repository.name }}
          pull: true


#  deployAppToDev:
#    name: Deploy app to dev
#    permissions:
#      packages: read
#      contents: read
#      id-token: write
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      # Deploy to dev-gcp
#      - name: Deploy to dev-gcp
#        uses: nais/deploy/actions/deploy@v2
#        env:
#          CLUSTER: dev-gcp
#          RESOURCE: .nais/dev.yaml
#          TEAM: pensjonsamhandling

#  "deployAppToDev-Q2":
#    name: Deploy app to dev-q2
#    permissions:
#      packages: read
#      contents: read
#      id-token: write
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      # Deploy to dev-gcp
#      - name: Deploy to dev-gcp
#        uses: nais/deploy/actions/deploy@v2
#        env:
#          CLUSTER: dev-gcp
#          RESOURCE: .nais/dev-q2.yaml
#          TEAM: pensjonsamhandling
#
#  "deployAppToProd":
#    name: Deploy app to Prod
#    permissions:
#      packages: read
#      contents: read
#      id-token: write
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      # Deploy to prod-gcp
#      - name: Deploy to prod-gcp
#        uses: nais/deploy/actions/deploy@v2
#        env:
#          CLUSTER: prod-gcp
#          RESOURCE: .nais/prod.yaml
#          TEAM: pensjonsamhandling
