name: "Build and deploy afp-offentlig"

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and release
    permissions:
      packages: write
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: temurin

      # Build
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gradle clean build


      - name: Create tag
        run: echo "TAG=$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: "Login to GitHub Docker Registry"
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.TAG }}


  deployAppToDev:
    name: Deploy app to dev
    permissions:
      packages: read
      contents: read
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Deploy to dev-gcp
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev.yaml
          IMAGE: ghcr.io/${{ github.repository }}:${{ env.TAG }}
          TEAM: pensjonsamhandling

  "deployAppToDev-Q2":
    name: Deploy app to dev-q2
    permissions:
      packages: read
      contents: read
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Deploy to dev-gcp
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev-q2.yaml
          IMAGE: ghcr.io/${{ github.repository }}:${{ env.TAG }}
          TEAM: pensjonsamhandling

  "deployAppToProd":
    name: Deploy app to Prod
    permissions:
      packages: read
      contents: read
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Deploy to prod-gcp
      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/prod.yaml
          IMAGE: ghcr.io/${{ github.repository }}:${{ env.TAG }}
          TEAM: pensjonsamhandling
