name: "Build and deploy afp-offentlig"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  build:
    name: Build and release
    permissions:
      packages: write
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: tyriis/docker-image-tag-exists@v2.1.0
        id: check-tag
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}
          tag: ${{ github.sha }}

      - uses: actions/checkout@v4
        if: ${{ steps.check-tag.outputs.tag != 'found' }}
      - uses: actions/setup-java@v4
        if: ${{ steps.check-tag.outputs.tag != 'found' }}
        with:
          java-version: 18
          distribution: temurin

      # Build
      - name: Build
        if: ${{ steps.check-tag.outputs.tag != 'found' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gradle clean build

      - name: Login to GitHub Docker Registry
        if: ${{ steps.check-tag.outputs.tag != 'found' }}
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        if: ${{ steps.check-tag.outputs.tag != 'found' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}


  deployAppToDev:
    name: Deploy app to dev
    permissions:
      packages: read
      contents: read
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Deploy to dev-gcp
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev.yaml
          TEAM: pensjonsamhandling

  "deployAppToDev-Q2":
    name: Deploy app to dev-q2
    permissions:
      packages: read
      contents: read
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Deploy to dev-gcp
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev-q2.yaml
          TEAM: pensjonsamhandling

  "deployAppToProd":
    name: Deploy app to Prod
    permissions:
      packages: read
      contents: read
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Deploy to prod-gcp
      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/prod.yaml
          TEAM: pensjonsamhandling
